"""
Problem 2: Even Fibonacci numbers

Desc: Each new term in the fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89

Problem: By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.        
"""

n1, n2, sum = 1, 2, 0

while n1<4000000:

    if not (n1 % 2 == 1):
        sum += n1

    n3 = n2+n1
    n1,n2 = n2, n3

print(sum)