"""
Problem 2: Even Fibonacci numbers.
Desc: Each new term in the fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89

Problem: By considering the terms in the Fibonacci sequence whose values do not exceed 4 million, \
find the sum of the even-valued terms.
"""

N1, N2, SUM_ = 1, 2, 0

while N1 < 4000000:

    if N1 % 2 != 1:
        SUM_ += N1

    N3 = N2 + N1
    N1, N2 = N2, N3

print(SUM_)
